// Who is trusted, who is barred, and who is on the list — one table, persisted.
//
// WHY THIS IS NOT IN THE WORLD SAVE, which was the first instinct and is wrong:
// the world save is where the world's own rules live (difficulty, cheats), and the
// argument for putting operators beside them is that they look like rules. They are
// not. Being an operator is a statement about a PERSON — that you trust this friend
// with your world — and it does not stop being true when you open a different one.
// A host who ops somebody, makes a new world an hour later and finds them demoted
// has been told something false about what opping meant.
//
// So it is one file for the installation, at data/access.json, which is also
// exactly what the dedicated server will read when it arrives: a server hosts one
// world at a time and swaps it without its operator list evaporating.
//
// ONE TABLE, THREE FLAGS, rather than the three separate lists Minecraft keeps
// (ops.json, banned-players.json, whitelist.json). A person is a row. Three lists
// means the same name can be spelled three ways in three files and the answer to
// "who is Ada" depends on which one you opened.
//
// HOW STRONG IS ANY OF THIS: not very, and it should be said plainly. A player id
// is generated by the client and kept in its own settings, and a display name is
// whatever a peer claims at the handshake. Neither is proof of identity, so a ban
// stops somebody who does not want to come back, not somebody determined to. That
// is the same guarantee the rest of the LAN path offers — this is a game on a local
// network, not an authenticated service — and the whitelist is the control that
// actually holds, because it refuses everybody who is not named rather than trying
// to enumerate everybody who is unwelcome.

#pragma once

#include <string>
#include <vector>

#include "cmd/command.h"

namespace hr::cmd {

// Enough for any LAN game and any list a person maintains by hand, and a bound so
// a hostile or broken file cannot make the game allocate without limit.
inline constexpr std::size_t kMaxAccessEntries = 512;

// One person. A row exists as soon as anything is recorded about them, and is
// dropped again when nothing is: level Anyone, not banned, not listed.
struct AccessEntry {
  // Empty for somebody who has never connected — banning a name before its owner
  // arrives has to work, because that is when you usually want to.
  std::string playerId;
  std::string name;
  Level level = Level::Anyone;
  bool banned = false;
  bool allowed = false;  // named on the whitelist
  std::string reason;    // why banned, shown at the refusal
};

class Access {
 public:
  // Every question the rest of the game asks, by id when there is one and by name
  // otherwise. An id match always wins: a name can be changed between sessions and
  // an id cannot be, so somebody who renames themselves keeps their level rather
  // than quietly losing it.
  Level levelOf(const std::string& playerId, const std::string& name = {}) const;
  bool banned(const std::string& playerId, const std::string& name = {}) const;

  // The one question the handshake asks. False fills `reason` with what to show at
  // the join screen, which is the only thing the refused peer will ever see.
  bool mayJoin(const std::string& playerId, const std::string& name, std::string& reason) const;

  // Each returns false only when the table is full. `name` may be empty when an id
  // is known and vice versa; a row learns the other half the first time both are
  // seen together, which is how a ban typed against a name starts covering that
  // person's id once they connect.
  bool setLevel(const std::string& playerId, const std::string& name, Level level);
  bool setBanned(const std::string& playerId, const std::string& name, bool on,
                 const std::string& reason);
  bool setAllowed(const std::string& playerId, const std::string& name, bool on);
  // Ties an id to the row that already names somebody, without recording anything
  // new about them. This is what makes a ban or a grant typed against a bare name —
  // which is how they are always typed, because a name is what the typist knows —
  // start covering that person's id the first time they connect under it, and so
  // keep covering them after they rename themselves.
  //
  // Deliberately not done inside mayJoin(): that is a question, and a question that
  // rewrites the file is one nobody can ask twice safely. Returns true when
  // something actually changed, so the caller knows whether to save.
  bool remember(const std::string& playerId, const std::string& name);

  bool whitelistEnabled() const { return whitelist_; }
  void setWhitelistEnabled(bool on) { whitelist_ = on; }

  const std::vector<AccessEntry>& entries() const { return entries_; }

  // Reads the file. A missing file is not an error — it means a fresh install with
  // nobody trusted and nobody barred, which is the right starting state. A
  // malformed one is logged and treated the same way, deliberately: refusing to
  // start because a hand-edited list has a stray comma would lock the owner out of
  // their own server.
  void load(const std::string& path);
  bool save() const;
  // Whether anything is recorded at all. save() writes the file regardless, so a
  // server operator can see the shape of it before editing by hand.
  bool empty() const { return entries_.empty() && !whitelist_; }

  // Serialises to the exact text save() writes, for the round-trip test.
  std::string toJson() const;
  // Parses that text back. False on a malformed document, leaving this untouched.
  bool fromJson(const std::string& text, std::string* errorOut = nullptr);

 private:
  AccessEntry* find(const std::string& playerId, const std::string& name);
  const AccessEntry* find(const std::string& playerId, const std::string& name) const;
  // Creates the row if there is room, or returns null when the table is full.
  AccessEntry* touch(const std::string& playerId, const std::string& name);
  // Drops a row that no longer says anything, so a pardon does not leave the file
  // growing a line per person who was briefly banned.
  void prune();

  std::vector<AccessEntry> entries_;
  bool whitelist_ = false;
  std::string path_;
};

}  // namespace hr::cmd
