# Run with: cmake -DASSET_DIR=... -DOUTPUT=... -P gen_assets.cmake
#
# Emits a C++ translation unit holding every asset as a byte array plus a lookup
# table keyed by the asset's path relative to ASSET_DIR (forward slashes).

if(NOT ASSET_DIR OR NOT OUTPUT)
  message(FATAL_ERROR "gen_assets.cmake needs -DASSET_DIR and -DOUTPUT")
endif()

file(GLOB_RECURSE files RELATIVE ${ASSET_DIR} ${ASSET_DIR}/*)
list(FILTER files EXCLUDE REGEX "/\\.")
list(SORT files)

set(body "// Generated by cmake/gen_assets.cmake — do not edit.\n")
string(APPEND body "#include \"core/assets.h\"\n\nnamespace hr::assets {\nnamespace {\n\n")

set(index 0)
set(table "")
foreach(rel IN LISTS files)
  if(IS_DIRECTORY ${ASSET_DIR}/${rel})
    continue()
  endif()

  # HEX then split into 0x.. bytes. Slower than a binary tool but keeps the
  # generator to plain CMake, and the asset set is small (kilobytes of shaders,
  # plus two fonts).
  file(READ ${ASSET_DIR}/${rel} hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
  string(LENGTH "${hex}" hexlen)
  math(EXPR size "${hexlen} / 2")

  # Wrap so MSVC does not choke on a single multi-megabyte source line.
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
         "\\1\n    " bytes "${bytes}")

  string(APPEND body "const unsigned char kData${index}[] = {\n    ${bytes}\n};\n")
  string(APPEND table "    { \"${rel}\", kData${index}, ${size}u },\n")
  math(EXPR index "${index} + 1")
endforeach()

string(APPEND body "\n}  // namespace\n\n")
if(index EQUAL 0)
  string(APPEND body "const Entry kEmbedded[] = { { nullptr, nullptr, 0 } };\n")
  string(APPEND body "const unsigned kEmbeddedCount = 0;\n")
else()
  string(APPEND body "const Entry kEmbedded[] = {\n${table}};\n")
  string(APPEND body "const unsigned kEmbeddedCount = ${index}u;\n")
endif()
string(APPEND body "\n}  // namespace hr::assets\n")

file(WRITE ${OUTPUT} "${body}")
message(STATUS "gen_assets: embedded ${index} file(s)")
